#!/usr/bin/env bash
d/magento dev:urn-catalog:generate misc.xml
d/copyfromcontainer misc.xml
mkdir -p src/.idea
mv src/misc.xml src/.idea/misc.xml 

echo "URN's have been generated, you may now restart PHPStorm"
