#!/usr/bin/env bash

[ -z "$1" ] && echo "Please specify test type (ex. integration)" && exit

TEST_TYPE="$1"
shift
d/clinotty bash -c "cd dev/tests/${TEST_TYPE} && ../../../vendor/d/phpunit -c phpunit.xml.dist $*"
