#!/usr/bin/env bash

if docker compose version >/dev/null 2>&1; then
  DOCKER_COMPOSE="docker compose"
else
  DOCKER_COMPOSE="docker-compose"
fi

COMPOSE_FILES=("compose.yaml")

if [ -f "compose.server.yaml" ]; then
  COMPOSE_FILES+=("compose.server.yaml")
else
  COMPOSE_FILES+=("compose.local.yaml")
fi

COMPOSE_FILES_PREFIXED=()
for file in "${COMPOSE_FILES[@]}"; do
  COMPOSE_FILES_PREFIXED+=("-f" "$file")
done

${DOCKER_COMPOSE} "${COMPOSE_FILES_PREFIXED[@]}" "$@"
