#!/usr/bin/env bash

EDITION=${1:-community}

# Define ANSI escape codes for colors
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

if [ -d ] && [ "$(ls -A ./src)" ]; then
  echo "Error: The \"src\" directory is not empty. Please remove all contents within this directory and try again."
  exit 1
fi

d/stop

d/start --no-dev
[ $? != 0 ] && echo "Failed to start Docker services" && exit

d/setup-composer-auth

d/fixowns

if [ "$EDITION" == "mageos" ]; then
  VERSION=${2:-1.0.5}
  d/clinotty composer create-project --repository-url=https://repo.mage-os.org/ mage-os/project-community-edition="${VERSION}" .
else
  VERSION=${2:-2.4.7-p3}
  d/clinotty composer create-project --repository=https://repo.magento.com/ magento/project-"${EDITION}"-edition="${VERSION}" .
fi

if [ $? != 0 ]; then
    echo -e "${BLUE}Please check the installation guide at ${YELLOW}https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty${BLUE} for troubleshooting.${NC}"
else
    d/clinotty [ ! -f "./var/composer_home/auth.json" ] && d/clinotty mkdir -p ./var/composer_home && d/clinotty cp /var/www/.composer/auth.json ./var/composer_home/auth.json
fi
