#!/usr/bin/env bash
echo "Fixing filesystem permissions..."

if [ -z "$1" ]; then
  d/bash find var vendor pub/static pub/media app/etc \( -type f -or -type d \) -exec chmod u+w {} +;
  d/bash chmod u+x bin/magento
else
  d/bash find "$1" \( -type f -or -type d \) -exec chmod u+w {} +;
fi

echo "Filesystem permissions fixed."
