#!/usr/bin/env bash
echo "Fixing filesystem permissions..."

if [ -z "$1" ]; then
  d/clinotty find var vendor pub/static pub/media app/etc \( -type f -or -type d \) -exec chmod u+w {} +;
  d/clinotty chmod u+x d/magento
else
  d/clinotty find "$1" \( -type f -or -type d \) -exec chmod u+w {} +;
fi

echo "Filesystem permissions fixed."
