#!/usr/bin/env bash

# shellcheck source=../env/db.env
source env/db.env
if [ -t 0 ]; then
  # Need tty to run mysql shell
  d/cli mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" "$@"
else
  # Read from stdin, ex: d/mysql < dbdump.sql
  d/clinotty mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" "$@"
fi
