#!/usr/bin/env bash
[ $# -eq 0 ] && echo "Please specify at least one domain (ex. mydomain.test)" && exit

# Generate certificate authority if not already setup
if ! d/docker-compose exec -T -u root app cat /root/.local/share/mkcert/rootCA.pem | grep -q 'BEGIN CERTIFICATE'; then
  d/setup-ssl-ca
fi

# Initialize an empty array to hold the processed domains
DOMAINS_WITHOUT_PORT=()

# Loop through each domain
for domain in "$@"; do
  # Strip out the port number
  DOMAIN_WITHOUT_PORT=$(echo "$domain" | cut -d ':' -f1)
  # Append the processed domain to the array
  DOMAINS_WITHOUT_PORT+=("$DOMAIN_WITHOUT_PORT")
done

# Use the array in the mkcert command
d/docker-compose exec -T -u root app mkcert -key-file nginx.key -cert-file nginx.crt "${DOMAINS_WITHOUT_PORT[@]}"

echo "Moving key and cert to /etc/nginx/certs/..."
d/docker-compose exec -T -u root app chown app:app nginx.key nginx.crt
d/docker-compose exec -T -u root app mv nginx.key nginx.crt /etc/nginx/certs/

# Restart nginx to apply the updates
echo "Restarting containers to apply updates..."
d/restart
