#!/usr/bin/env bash
[ -z "$1" ] && echo "Please specify a domain (ex. mydomain.test)" && exit

# Generate certificate authority if not already setup
if ! d/docker-compose exec -T -u root nginx cat /root/.local/share/mkcert/rootCA.pem | grep -q 'BEGIN CERTIFICATE'; then
  echo 'executing ssl-ca command'
  d/setup-ssl-ca
fi

# Generate the certificate for the specified domain
DOMAIN_WITHOUT_PORT=$(echo "$@" | cut -d ':' -f1)
d/docker-compose exec -T -u root nginx mkdir -p /etc/nginx/certs
d/docker-compose exec -T -u root nginx mkcert -key-file /etc/nginx/certs/nginx.key -cert-file /etc/nginx/certs/nginx.crt "$DOMAIN_WITHOUT_PORT"
echo "Setting ownership on /etc/nginx/certs/nginx.key and /etc/nginx/certs/nginx.crt..."
d/docker-compose exec -T -u root nginx chown app:app /etc/nginx/certs/nginx.key /etc/nginx/certs/nginx.crt

# Restart nginx to apply the updates
echo "Restarting containers to apply updates..."
d/restart
