services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.file.directory=/etc/traefik/dynamic
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ssldata:/certs:ro
      - ./docker/traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
    networks:
      - pointeger
    restart: unless-stopped
  nginx:
    volumes:
      - ./docker/nginx/conf/default-dev.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./docker/.env.local
    networks:
      - pointeger

  varnish:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=pointeger"
      - "traefik.http.services.magento.loadbalancer.server.port=6081"
      - "traefik.http.routers.magento.rule=Host(`magento.test`,`magento2.test`)"
      - "traefik.http.routers.magento.entrypoints=websecure"
      - "traefik.http.routers.magento.tls=true"
      - "traefik.http.routers.magento-http.rule=Host(`magento.test`,`magento2.test`)"
      - "traefik.http.routers.magento-http.entrypoints=web"
      - "traefik.http.routers.magento-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    networks:
      - pointeger

  phpfpm:
    env_file:
      - ./docker/.env.local
    networks:
      - pointeger

  phpfpm-xdebug:
    image: pointeger/magento-php-xdebug:8.2
    environment:
      - TZ=Asia/Karachi
    volumes:
      - ./src/:/var/www/html
      - ./docker/xdebug/php.ini:/usr/local/etc/php/php.ini
      - sockdata:/sock
    env_file:
      - ./docker/.env.local
      - ./docker/xdebug/.env
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - pointeger

  db:
    ports:
      - "3306:3306"
    env_file: ./docker/db/.env
    networks:
      - pointeger

  adminer:
    image: adminer
    ports:
      - 8082:8080
    networks:
      - pointeger

  redis:
    ports:
      - "6379:6379"
    networks:
      - pointeger

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - pointeger

#  opensearch:
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    env_file: ./docker/opensearch/.env
#    networks:
#      - pointeger
#    ## Uncomment following if you are using Apple M4 based chip and MacOs version 15.2
#    environment:
#     - "_JAVA_OPTIONS=-XX:UseSVE=0"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 587:587
      - 8025:8025
      - 1025:1025
    networks:
      - pointeger

networks:
  pointeger:
    driver: bridge
