services:
  nginx:
    image: pointeger/magento-nginx:1.24.1
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html:ro
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    depends_on:
      - phpfpm
  
  phpfpm:
    image: pointeger/magento-php:8.2
    environment:
      - TZ=Asia/Karachi
    volumes:
      - ./src/:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - sockdata:/sock
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: mariadb:10.6.18
    environment:
      - TZ=Asia/Karachi
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7.2-alpine

  elasticsearch:
#    container_name: albarak-mage-elasticsearch
    image: markoshust/magento-elasticsearch:7.16-0
    env_file: .docker/elasticsearch/.env
    environment:
        - "discovery.type=single-node"
        ## Avoid test failures due to small disks
        ## More info at https://github.com/markshust/docker-magento/issues/488
        - "cluster.routing.allocation.disk.threshold_enabled=false"
        - "index.blocks.read_only_allow_delete"
        ## Uncomment to set custom heap size to avoid memory errors
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ## Uncomment to increase the virtual memory map count
        #- "max_map_count=262144"
        ## Uncomment the line below if ElasticSearch fails to start and stops after ~150 seconds with the error "container for service "elasticsearch" is unhealthy".
        - "xpack.security.enabled=false"
        - "ELASTICSEARCH_HOST=elasticsearch"
        # Disable geoip downloader to avoid failures(losing indices on the server)
        - "ingest.geoip.downloader.enabled=false"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data/

volumes:
  dbdata:
  sockdata:
  ssldata:
  elasticsearchdata:
