services:
  app:
    volumes: &appvolumes
      - ./env/nginx/nginx.local.conf:/var/www/html/nginx.conf:cached

  phpfpm:
    volumes: *appvolumes

  ssh:
    image: markoshust/ssh
    ports:
      - "22:22"
    volumes: *appvolumes
